### ISSUE TITLE
dist/UnpackDarkSoulsForModding.exe is incompatible with Windows 7 x64

### ISSUE THREAD

**Issue by figlesias** [HotPocketRemix/UnpackDarkSoulsForModding#1]
The following fatal error comes up when trying to run:

"The version of this file is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need an x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher."

**Comment by HotPocketRemix** [comment]
I'm not sure what would be causing this. I'm using 64-bit Windows 7 myself, so I'm fairly confident that's not the issue.

**Comment by figlesias** [comment]
Hello again - just wanted to follow up that I tried this again with the Jul 30 release and it has worked perfectly. Maybe I just had a corrupted download the first time around, since nobody else seems to have had this issue. Thanks!
