### ISSUE TITLE
Script crashes at a specific point - Windows 10

### ISSUE THREAD

**Issue by bladomas** [HotPocketRemix/UnpackDarkSoulsForModding#3]
Whenever I try to launch the newest version it ends up exiting too early due to a failure. (The older version I still have does not cause this crash but it does not handle DCX-compression. The line on which it starts crashing is modifying .exe file I believe. After the transmutations it gives:
Traceback:
unpack_dark_souls_for_modding.py line 13 in module
unpacker_file_handler.py line 552 in attempt_unpack
unpacker_file_handler.py line 222 in modify_exe
ValueError: unknown .exe version byte.
Failed to execute script unpack_dark_souls_for_modding

(I shortened it a tiny bit. I had to time printscreen right when it crashes, since it closes very fast)

Conclusion edit: Don't use beta on steam

**Comment by bladomas** [comment]
[Doc2.docx](https://github.com/HotPocketRemix/UnpackDarkSoulsForModding/files/1177529/Doc2.docx)
First screenshot is the new script, 2nd one is the older one, last one is the one downloaded from here (opposed to nexus mods for first one).

**Comment by HotPocketRemix** [comment]
Can you upload your `unpackDS-latestlog.txt` to pastebin or something and give me the link?

**Comment by bladomas** [comment]
[unpackDS-latestlog.txt](https://github.com/HotPocketRemix/UnpackDarkSoulsForModding/files/1177670/unpackDS-latestlog.txt)
Here it is, sorry about the delay, was away.

**Comment by bladomas** [comment]
Made a mistake, uploaded wrong one give me a sec
edit: will take 3 minutes.

**Comment by bladomas** [comment]
[unpackDS-latestlog.txt](https://github.com/HotPocketRemix/UnpackDarkSoulsForModding/files/1177682/unpackDS-latestlog.txt)
edit: The reason why it asks to replace the folders is because I ran the older version beforehand. I copied the backup files back into DATA and ran.

**Comment by HotPocketRemix** [comment]
Your .exe has an unexpected checksum. Have you modified the .exe in any way from the default Steam .exe that you can think of?

It's currently throwing the error because it doesn't recognize the .exe version, so it can't figure out where to patch the bytes that disable DCX compression.

**Comment by bladomas** [comment]
Nope, I have not modified it. Only installed the beta version in steam. I reinstalled it a couple of times and enabled the beta. Without it, it got stuck early on.

**Comment by HotPocketRemix** [comment]
Okay, it's probably the beta version that's messing it up, the beta is quite out-of-date. What was going wrong with the normal .exe?

**Comment by bladomas** [comment]
I use dsptde 2.0. I always used it so I never thought about it. Will try without it again.
edit: No initial error with exe file anymore. Maybe I was just using a habit I had (of using beta)

**Comment by bladomas** [comment]
This is weird. After trying with beta initially, I tried without it and the script was stuck on the first step, waiting maybe 15 minutes (usually takes max 1 min). And now the script is running fine. 
Edit: It finished without issues. To think that I wasted on this over 3 hours... Anyway, much appreciated for your help and sorry to have wasted some of your time.
